services:
  - type: web
    name: app-player
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: RATE_LIMITER_ENABLED
        value: false 